save: False 
seed: 4321
batch_size: 24
n_epochs1: 6
n_epochs2: 10
learning_rate1: 1e-3
learning_rate2: 1e-5


model: 'dbmdz/bert-base-italian-xxl-uncased'
#'dbmdz/bert-base-italian-xxl-uncased'
#'xlm-roberta-large'
#'m-polignano-uniba/bert_uncased_L-12_H-768_A-12_italian_alb3rt0'
#'dbmdz/bert-base-italian-xxl-uncased'
#'bert-base-multilingual-cased'

loss_weights: [ 0.45351118,  2.61287177,  1.48407643,  7.53686636,  2.20779221, 1.88776306]